# Generated by Django 4.0.3 on 2022-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
